# Generated by Django 3.2.9 on 2021-11-24 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_groupchat_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupchat',
            name='created',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
