# Generated by Django 3.2.9 on 2021-11-24 14:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0006_auto_20211124_1506'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messages',
            name='group',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='chat.groupchat'),
        ),
    ]
