# Generated by Django 3.2.9 on 2021-11-25 12:19

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0007_alter_messages_group'),
    ]

    operations = [
        migrations.RenameField(
            model_name='messages',
            old_name='date',
            new_name='date_created',
        ),
        migrations.AddField(
            model_name='messages',
            name='date_posted',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 11, 25, 12, 19, 42, 2003, tzinfo=utc)),
        ),
        migrations.AddField(
            model_name='messages',
            name='is_anonymous',
            field=models.BooleanField(default=False),
        ),
    ]
