# Generated by Django 3.2.9 on 2021-11-25 14:01

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0010_alter_messages_date_posted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messages',
            name='date_posted',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 11, 25, 14, 1, 50, 208171, tzinfo=utc)),
        ),
    ]
